# Generated by Django 5.0.7 on 2024-07-26 19:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("site_setup", "0002_setesetup"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SeteSetup",
            new_name="SiteSetup",
        ),
    ]
