# Generated by Django 5.0.7 on 2024-07-27 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_setup", "0003_rename_setesetup_sitesetup"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sitesetup",
            options={"verbose_name": "setup", "verbose_name_plural": "setup"},
        ),
        migrations.AddField(
            model_name="menulink",
            name="site_setup",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="site_setup.sitesetup",
            ),
        ),
    ]
