# Generated by Django 5.0.7 on 2024-07-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_setup", "0004_alter_sitesetup_options_menulink_site_setup"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesetup",
            name="favicon",
            field=models.ImageField(default="", upload_to="assets/favicon/%Y%m/"),
        ),
    ]
